# Importing important library

In [1]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

# Data Loading

In [3]:
df=pd.read_csv('cleaned_superstore.csv')

# Count all rows and columns

In [3]:
df.shape

(51290, 26)

# Basic information of Data

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51290 entries, 0 to 51289
Data columns (total 26 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Category        51290 non-null  object
 1   City            51290 non-null  object
 2   Country         51290 non-null  object
 3   Customer.ID     51290 non-null  object
 4   Customer.Name   51290 non-null  object
 5   Discount        51290 non-null  float64
 6   Market          51290 non-null  object
 7   Order.Date      51290 non-null  object
 8   Order.ID        51290 non-null  object
 9   Order.Priority  51290 non-null  object
 10  Product.ID      51290 non-null  object
 11  Product.Name    51290 non-null  object
 12  Profit          51290 non-null  float64
 13  Quantity        51290 non-null  int64
 14  Region          51290 non-null  object
 15  Row.ID          51290 non-null  int64
 16  Sales           51290 non-null  int64
 17  Segment         51290 non-null  object
 18  Ship.Date       51290 non-null  object
 19  Ship.Mode       51290 non-null  object
 20  Shipping.Cost   51290 non-null  float64
 21  State           51290 non-null  object
 22  Sub.Category    51290 non-null  object
 23  Year            51290 non-null  int64
 24  Market2         51290 non-null  object
 25  weeknum         51290 non-null  int64
dtypes: float64(3), int64(5), object(18)
memory usage: 10.2+ MB

# Object column converted into Date

In [28]:
df['Order.Date'] = pd.to_datetime(df['Order.Date'])
df['Ship.Date'] = pd.to_datetime(df['Ship.Date'])

df.head()

,Category,City,Country,Customer.ID,Customer.Name,Discount,Market,Order.Date,Order.ID,Order.Priority,...,Ship.Date,Ship.Mode,Shipping.Cost,State,Sub.Category,Year,Market2,weeknum,Discount_Range,Revenue
0,Office Supplies,Los Angeles,United States,LS-172304,Lycoris Saunders,0.0,US,2011-01-07,CA-2011-130813,High,...,2011-01-09,Second Class,4.37,California,Paper,2011,North America,2,0-10%,57
1,Office Supplies,Los Angeles,United States,MV-174854,Mark Van Huff,0.0,US,2011-01-21,CA-2011-148614,Medium,...,2011-01-26,Standard Class,0.94,California,Paper,2011,North America,4,0-10%,38
2,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,2011-08-05,CA-2011-118962,Medium,...,2011-08-09,Standard Class,1.81,California,Paper,2011,North America,32,0-10%,63
3,Office Supplies,Los Angeles,United States,CS-121304,Chad Sievert,0.0,US,2011-08-05,CA-2011-118962,Medium,...,2011-08-09,Standard Class,4.59,California,Paper,2011,North America,32,0-10%,222
4,Office Supplies,Los Angeles,United States,AP-109154,Arthur Prichep,0.0,US,2011-09-29,CA-2011-146969,High,...,2011-10-03,Standard Class,1.32,California,Paper,2011,North America,40,0-10%,6

In [6]:
df.describe()

,Discount,Order.Date,Profit,Quantity,Row.ID,Sales,Ship.Date,Shipping.Cost,Year,weeknum
count,51290.000000,51290,51290.000000,51290.000000,51290.00000,51290.000000,51290,51290.000000,51290.000000,51290.000000
mean,0.142908,2013-05-11 21:26:49.155780864,28.610982,3.476545,25645.50000,246.498440,2013-05-15 20:42:42.745174784,26.375818,2012.777208,31.287112
min,0.000000,2011-01-01 00:00:00,-6599.978000,1.000000,1.00000,0.000000,2011-01-03 00:00:00,0.002000,2011.000000,1.000000
25%,0.000000,2012-06-19 00:00:00,0.000000,2.000000,12823.25000,31.000000,2012-06-23 00:00:00,2.610000,2012.000000,20.000000
50%,0.000000,2013-07-08 00:00:00,9.240000,3.000000,25645.50000,85.000000,2013-07-12 00:00:00,7.790000,2013.000000,33.000000
75%,0.200000,2014-05-22 00:00:00,36.810000,5.000000,38467.75000,251.000000,2014-05-26 00:00:00,24.450000,2014.000000,44.000000
max,0.850000,2014-12-31 00:00:00,8399.976000,14.000000,51290.00000,22638.000000,2015-01-07 00:00:00,933.570000,2014.000000,53.000000
std,0.212280,NaN,174.340972,2.278766,14806.29199,487.567175,NaN,57.296810,1.098931,14.429795

# Check Null Value

In [7]:
df.isnull().sum()

Category          0
City              0
Country           0
Customer.ID       0
Customer.Name     0
Discount          0
Market            0
Order.Date        0
Order.ID          0
Order.Priority    0
Product.ID        0
Product.Name      0
Profit            0
Quantity          0
Region            0
Row.ID            0
Sales             0
Segment           0
Ship.Date         0
Ship.Mode         0
Shipping.Cost     0
State             0
Sub.Category      0
Year              0
Market2           0
weeknum           0
dtype: int64

# Check Duplicate values

In [8]:
df.duplicated().sum()

np.int64(0)

# Outliers identify karo (Sales, Profit, Discount).

In [9]:
columns = ['Sales', 'Profit', 'Discount']

for col in columns:
    Q1 = df[col].quantile(0.25)
    Q3 = df[col].quantile(0.75)
    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = df[(df[col] < lower) | (df[col] > upper)]

    print(f"{col} Outliers: {len(outliers)}")

Sales Outliers: 5655
Profit Outliers: 9755
Discount Outliers: 4172

# Total Revenue, Profit aur Profit Margin kya hai?

In [10]:
total_profit=df['Profit'].sum().round(2)
print("\nTotal Profit:\n",total_profit)

total_revenue=df['Sales'].sum()
print("\nTotal Revenue:\n",total_revenue)

profit_margin=(total_profit/total_revenue)*100
profit_margin=profit_margin.round(2)
print('\nProfit Margin:\n',profit_margin)

Total Profit:
 1467457.29

Total Revenue:
 12642905

Profit Margin:
 11.61

# Average Order Value kya hai?

In [11]:
total_sales=df['Sales'].sum()
total_orders=df['Order.ID'].nunique()

aov=total_sales/total_orders

print("Average Order Value:\n",round(aov, 2))

Average Order Value:
 505.01

# Revenue per Customer kitna hai?

In [12]:
revenue_per_customer=df.groupby('Customer.Name')['Sales'].sum()
print("\nRevuene per Customer:\n",revenue_per_customer)

Revuene per Customer:
 Customer.Name
Aaron Bergman         24646
Aaron Hawkins         20759
Aaron Smayling        14207
Adam Bellavance       20189
Adam Hart             21720
                      ...
Xylona Preis          12202
Yana Sorensen         20034
Yoseph Carroll        20165
Zuschuss Carroll      28485
Zuschuss Donatelli    12434
Name: Sales, Length: 795, dtype: int64

# Revenue per Product kitna hai?

In [13]:
revenue_per_product=df.groupby('Product.Name')['Sales'].sum()
print('\nRevenue per Product:\n',revenue_per_product)

Revenue per Product:
 Product.Name
"While you Were Out" Message Book, One Form per Page                                                     25
#10 Gummed Flap White Envelopes, 100/Box                                                                 42
#10 Self-Seal White Envelopes                                                                           109
#10 White Business Envelopes,4 1/8 x 9 1/2                                                              489
#10- 4 1/8" x 9 1/2" Recycled Envelopes                                                                 285
                                                                                                       ...
iKross Bluetooth Portable Keyboard + Cell Phone Stand Holder + Brush for Apple iPhone 5S 5C 5, 4S 4     479
iOttie HLCRIO102 Car Mount                                                                              216
iOttie XL Car Mount                                                                                     224
invisibleSHIELD by ZAGG Smudge-Free Screen Protector                                                    442
netTALK DUO VoIP Telephone Service                                                                     1113
Name: Sales, Length: 3788, dtype: int64

# Monthly Revenue Growth Rate kya hai?

In [14]:
monthly_revenue=df.groupby(df['Order.Date'].dt.to_period('M'))['Sales'].sum().reset_index()

monthly_revenue['growth_rate']=monthly_revenue['Sales'].pct_change()*100

monthly_revenue.fillna(0).round(2)

   Order.Date   Sales  growth_rate
0     2011-01   98902         0.00
1     2011-02   91152        -7.84
2     2011-03  145726        59.87
3     2011-04  116927       -19.76
4     2011-05  146762        25.52
5     2011-06  215214        46.64
6     2011-07  115518       -46.32
7     2011-08  207570        79.69
8     2011-09  290230        39.82
9     2011-10  199070       -31.41
10    2011-11  298499        49.95
11    2011-12  333941        11.87
12    2012-01  135775       -59.34
13    2012-02  100521       -25.97
14    2012-03  163092        62.25
15    2012-04  161060        -1.25
16    2012-05  208370        29.37
17    2012-06  256181        22.95
18    2012-07  145247       -43.30
19    2012-08  303158       108.72
20    2012-09  289390        -4.54
21    2012-10  252942       -12.59
22    2012-11  323512        27.90
23    2012-12  338245         4.55
24    2013-01  199197       -41.11
25    2013-02  167247       -16.04
26    2013-03  198591        18.74
27    2013-04  177835       -10.45
28    2013-05  260525        46.50
29    2013-06  396513        52.20
30    2013-07  229940       -42.01
31    2013-08  326491        41.99
32    2013-09  376626        15.36
33    2013-10  293423       -22.09
34    2013-11  373996        27.46
35    2013-12  405476         8.42
36    2014-01  241267       -40.50
37    2014-02  184848       -23.38
38    2014-03  263110        42.34
39    2014-04  242781        -7.73
40    2014-05  288404        18.79
41    2014-06  401843        39.33
42    2014-07  258718       -35.62
43    2014-08  456633        76.50
44    2014-09  481186         5.38
45    2014-10  422785       -12.14
46    2014-11  555312        31.35
47    2014-12  503154        -9.39

# Monthly Sales Trend identify karo.

In [15]:
df['Month']=df['Order.Date'].dt.month_name()
monthly_sales_trend = df.groupby('Month')['Sales'].sum()

month_order = ['January', 'February', 'March', 'April', 'May', 'June',
               'July', 'August', 'September', 'October', 'November', 'December']

monthly_sales_trend = monthly_sales_trend.reindex(month_order)
monthly_sales_trend

Month
January       675141
February      543768
March         770519
April         698603
May           904061
June         1269751
July          749423
August       1293852
September    1437432
October      1168220
November     1551319
December     1580816
Name: Sales, dtype: int64

In [16]:
monthly_profit_trend=df.groupby('Month')['Profit'].sum()
print(monthly_profit_trend)

Month
April         73513.63124
August       151854.10972
December     170718.12710
February      70932.19922
January       73535.38454
July          78070.09172
June         147079.41684
March         94087.52096
May          104509.78428
November     175449.48412
October      157269.35838
September    170438.18316
Name: Profit, dtype: float64

# Seasonal patterns detect karo.

In [17]:
seasonal_pattern=df.groupby('Year')['Sales'].sum()
print('\nSeasonal Pattern:\n',seasonal_pattern)

Seasonal Pattern:
 Year
2011    2259511
2012    2677493
2013    3405860
2014    4300041
Name: Sales, dtype: int64

# Kis month me consistently best performance aati hai?

In [18]:
best_consistent_performance_month=df.groupby('Month')['Sales'].sum().sort_values(ascending=False)
print('\nBest consistently performer Month:\n',best_consistent_performance_month)

Best consistently performer Month:
 Month
December     1580816
November     1551319
September    1437432
August       1293852
June         1269751
October      1168220
May           904061
March         770519
July          749423
April         698603
January       675141
February      543768
Name: Sales, dtype: int64

# Month-over-Month Growth calculate karo.

In [19]:
month_sales=df.groupby('Month')['Sales'].sum()

month_over_month_growth=month_sales.pct_change()*100

month_over_month_growth=month_over_month_growth.fillna(0).round(2)

print('\nMonth Over Month:\n',month_over_month_growth)

Month Over Month:
 Month
April         0.00
August       85.21
December     22.18
February    -65.60
January      24.16
July         11.00
June         69.43
March       -39.32
May          17.33
November     71.59
October     -24.70
September    23.04
Name: Sales, dtype: float64

# Top 10 products by Revenue.

In [42]:
df['Revenue']=df['Sales']*df['Quantity']
products_by_revenue=df.groupby('Product.Name')['Revenue'].sum().sort_values(ascending=False).head(10)

print('\nTop 10 Product by Revenue:\n',products_by_revenue)

Top 10 Product by Revenue:
 Product.Name
Apple Smart Phone, Full Size                  432254
Motorola Smart Phone, Full Size               383087
Cisco Smart Phone, Full Size                  377351
Nokia Smart Phone, Full Size                  297166
Hon Executive Leather Armchair, Adjustable    295452
Samsung Smart Phone, VoIP                     280225
Canon imageCLASS 2200 Advanced Copier         253400
SAFCO Executive Leather Armchair, Black       253068
Samsung Smart Phone, Cordless                 245078
Nokia Smart Phone, with Caller ID             244869
Name: Revenue, dtype: int64

# Top 10 products by Profit.

In [21]:
products_by_profit=df.groupby('Product.Name')['Profit'].sum().sort_values(ascending=False).head(10)

print('\nTop 10 Product by Revenue:\n',products_by_profit)

Top 10 Product by Revenue:
 Product.Name
Canon imageCLASS 2200 Advanced Copier                       25199.9280
Cisco Smart Phone, Full Size                                17238.5206
Motorola Smart Phone, Full Size                             17027.1130
Hoover Stove, Red                                           11807.9690
Sauder Classic Bookcase, Traditional                        10672.0730
Harbour Creations Executive Leather Armchair, Adjustable    10427.3260
Nokia Smart Phone, Full Size                                 9938.1955
Cisco Smart Phone, with Caller ID                            9786.6408
Nokia Smart Phone, with Caller ID                            9465.3257
Belkin Router, USB                                           8955.0180
Name: Profit, dtype: float64

# Bottom 10 products by Profit.

In [22]:
products_by_profit=df.groupby('Product.Name')['Profit'].sum().sort_values(ascending=True).head(10)

print('\nBottom 10 Product by Revenue:\n',products_by_profit)

Bottom 10 Product by Revenue:
 Product.Name
Cubify CubeX 3D Printer Double Head Print                  -8879.9704
Lexmark MX611dhe Monochrome Laser Printer                  -4589.9730
Motorola Smart Phone, Cordless                             -4447.0380
Cubify CubeX 3D Printer Triple Head Print                  -3839.9904
Bevis Round Table, Adjustable Height                       -3649.8940
Bevis Computer Table, Fully Assembled                      -3509.5638
Rogers Lockers, Blue                                       -2893.4908
Chromcraft Bull-Nose Wood Oval Conference Tables & Bases   -2876.1156
Bevis Wood Table, with Bottom Storage                      -2782.5880
Lesro Training Table, Rectangular                          -2581.2834
Name: Profit, dtype: float64

# High Revenue but Low Profit products identify karo.

In [41]:
df['Revenue']=df['Sales']*df['Quantity']
product_analysis = df.groupby('Product.Name')[['Revenue','Profit']].sum().reset_index()

print('High Revenue but Low Profit:\n')
product_analysis.sort_values(['Revenue','Profit'], ascending=[False, True]).head(10)

High Revenue but Low Profit:

                                    Product.Name  Revenue      Profit
310                 Apple Smart Phone, Full Size   432254   5921.5786
2415             Motorola Smart Phone, Full Size   383087  17027.1130
970                 Cisco Smart Phone, Full Size   377351  17238.5206
2501                Nokia Smart Phone, Full Size   297166   9938.1955
1837  Hon Executive Leather Armchair, Adjustable   295452   5997.2541
2990                   Samsung Smart Phone, VoIP   280225   3903.8580
866        Canon imageCLASS 2200 Advanced Copier   253400  25199.9280
2903     SAFCO Executive Leather Armchair, Black   253068   7154.2800
2988               Samsung Smart Phone, Cordless   245078   -198.0900
2502           Nokia Smart Phone, with Caller ID   244869   9465.3257

# Low Revenue but High Profit products identify karo.

In [40]:
df['Revenue']=df['Sales']*df['Quantity']
product_analysis=df.groupby('Product.Name')[['Revenue','Profit']].sum().reset_index()

print('\nLow Revenue but High Profit products:\n')
product_analysis.sort_values(['Revenue', 'Profit'], ascending=[True, False]).head(10)

Low Revenue but High Profit products:

                                           Product.Name  Revenue  Profit
1368  Eureka Disposable Bags for Sanitaire Vibra Gro...        4 -4.4660
3707                                           Xerox 20        6  3.1104
373                                             Avery 5       12  2.8224
1641                                Grip Seal Envelopes       14  2.3868
679               Boston 1900 Electric Pencil Sharpener       15  4.4940
438   Avery Hi-Liter Pen Style Six-Color Fluorescent...       16  3.1570
434   Avery Hi-Liter Comfort Grip Fluorescent Highli...       16  3.0420
3694                                         Xerox 1989       16  2.6892
74         Acco Economy Flexible Poly Round Ring Binder       17 -5.7420
1922  Hoover Replacement Belt for Commercial Guardsm...       18  0.4440

# Category-wise Profit Margin compare karo.

In [25]:
total_profit=df.groupby('Category')['Profit'].sum()
total_sales=df.groupby('Category')['Sales'].sum()

category_wise_profit_margin=(total_profit/total_sales)*100

print(category_wise_profit_margin.head())

Category
Furniture           6.937795
Office Supplies    13.689693
Technology         13.989925
dtype: float64

# Top 20 customers by Revenue.

In [39]:
df['Revenue']=df['Sales']*df['Quantity']
customers_by_revenue=df.groupby('Customer.Name')['Revenue'].sum().sort_values(ascending=False).head(20)

print('\nTop 20 Customers by Revenue: \n',customers_by_revenue)

Top 20 Customers by Revenue:
 Customer.Name
Tom Ashbrook          226428
Greg Tran             216115
Christopher Conant    205432
Sean Miller           195861
Adrian Barton         186827
Dave Poirier          182885
Harry Greene          179114
Peter Fuller          178074
Harry Marie           176848
Tamara Chand          173246
Bill Eplett           171604
Dave Brooks           167200
Laurel Beltran        166732
Daniel Raglin         163821
Carol Adams           163408
Fred Hopkins          162788
Patrick O'Brill       161146
Maria Bertelson       160290
Vivek Grady           159096
Zuschuss Carroll      155718
Name: Revenue, dtype: int64

# Top 20 customers by Profit.

In [27]:
customers_by_profit=df.groupby('Customer.Name')['Profit'].sum().sort_values(ascending=False).head(20)

print('\nTop 20 Customers by Revenue:\n',customers_by_profit)

Top 20 Customers by Revenue:
 Customer.Name
Tamara Chand          8672.89890
Raymond Buch          8453.04950
Sanjit Chand          8205.37990
Hunter Lopez          7816.56778
Bill Eplett           7410.00530
Harry Marie           6958.28640
Susan Pistek          6484.40726
Mike Gockenbach       6458.67620
Adrian Barton         6417.28450
Tom Ashbrook          6311.97910
Jane Waco             6265.84570
Daniel Raglin         6103.97292
Sanjit Engle          6015.78392
Bill Shonely          5968.90736
Ellis Ballard         5848.74774
Nathan Mautz          5789.11680
Christopher Conant    5603.33370
Keith Dawkins         5486.17250
John Huston           5395.82370
Greg Tran             5214.13118
Name: Profit, dtype: float64

# Repeat vs One-Time Customers.

In [28]:
repeat_vs_one_time_cust=df.groupby('Customer.ID')['Order.ID'].count()
print('\nRepeat vs One Time Customer: \n',repeat_vs_one_time_cust)

Repeat vs One Time Customer:
 Customer.ID
AA-103151    10
AA-103152    16
AA-103153     5
AA-103154    11
AA-103751     9
             ..
ZD-119252     9
ZD-219251    10
ZD-219252    14
ZD-219253     3
ZD-219254     9
Name: Order.ID, Length: 4873, dtype: int64

# Customer Lifetime Revenue calculate karo.

In [38]:
df['Revenue']=df['Sales']*df['Quantity']
cust_life_time_rev=df.groupby('Customer.Name')['Revenue'].sum().sort_values(ascending=False)

print('\nCustomer life time Revenue:\n',cust_life_time_rev)

Customer life time Revenue:
 Customer.Name
Tom Ashbrook           226428
Greg Tran              216115
Christopher Conant     205432
Sean Miller            195861
Adrian Barton          186827
                        ...
Shaun Weien             22904
Robert Barroso          22768
Vivian Mathis           22418
Michael Oakman          17080
Catherine Glotzbach     15521
Name: Revenue, Length: 795, dtype: int64

In [30]:
customer_revenue = df.groupby('Customer.Name')['Sales'].sum()

customer_segment = np.where(
    customer_revenue > 30000, 'High',
    np.where(customer_revenue > 10000, 'Medium', 'Low')
)

customer_revenue.head()

Customer.Name
Aaron Bergman      24646
Aaron Hawkins      20759
Aaron Smayling     14207
Adam Bellavance    20189
Adam Hart          21720
Name: Sales, dtype: int64

# Kaun se customers loss generate kar rahe hain?

In [47]:
customer_profit=df.groupby('Customer.Name')['Profit'].sum()

loss_generated_cust=customer_profit[customer_profit<0]
loss_generated_cust

Customer.Name
Alan Haines         -592.24612
Allen Rosenblatt    -552.28182
Anna Chung          -272.12732
Becky Martin       -1096.92540
Bobby Trafton       -469.79110
                       ...
Tanja Norvell       -706.18216
Tracy Hopkins       -733.74750
Tracy Zic            -80.11550
Valerie Mitchum    -1645.79878
Vivek Gonzalez      -364.42470
Name: Profit, Length: 67, dtype: float64

# Region-wise Revenue and Profit.

In [37]:
df['Revenue']=df['Sales']*df['Quantity']

regional_wise_revenue=df.groupby('Region')['Revenue'].sum().sort_values(ascending=False)
print('\nRegional wise Revenue\n',regional_wise_revenue)

regional_wise_profit=df.groupby('Region')['Profit'].sum().sort_values(ascending=False)
print('\nRegional wise Profit\n',regional_wise_profit)

Regional wise Revenue
 Region
Central           14027202
South              8066936
North              6277834
Oceania            5715329
Southeast Asia     4373382
North Asia         4326608
Central Asia       3842741
West               3595417
East               3379498
EMEA               3317542
Africa             3130218
Caribbean          1532905
Canada              237288
Name: Revenue, dtype: int64

Regional wise Revenue
 Region
Central           311403.98164
North             194597.95252
North Asia        165578.42100
South             140355.76618
Central Asia      132480.18700
Oceania           120089.11200
West              108418.44890
East               91522.78000
Africa             88871.63100
EMEA               43897.97100
Caribbean          34571.32104
Southeast Asia     17852.32900
Canada             17817.39000
Name: Profit, dtype: float64

# State-wise Revenue Ranking.

In [44]:
df['Revenue']=df['Sales']*df['Quantity']

state_wise_revenue=df.groupby('State')['Revenue'].sum().sort_values(ascending=False)
print('\nState wise Revenue:\n',state_wise_revenue)

State wise Revenue:
 State
England               2462280
California            2301359
Ile-de-France         1601806
New York              1561203
New South Wales       1470745
                       ...
Pernik                     15
Manicaland                 12
Bitola                     11
Kabarole                    4
Matabeleland North          3
Name: Revenue, Length: 1094, dtype: int64

# State-wise Profit Ranking.

In [45]:
state_wise_profit=df.groupby('State')['Profit'].sum().sort_values(ascending=False)
print('\nState wise Profit:\n',state_wise_profit)

State wise Profit:
 State
England            99907.7310
California         76381.3871
New York           74038.5486
Ile-de-France      44055.9240
New South Wales    43695.9840
                      ...
Izmir             -15729.8040
Ohio              -16971.3766
Texas             -25729.3563
Lagos             -25922.5110
Istanbul          -29033.7000
Name: Profit, Length: 1094, dtype: float64

# Loss-making States identify karo.

In [46]:
state_profit=df.groupby('State')['Profit'].sum()

loss_making_state=state_profit[state_profit<0]
loss_making_state

State
'Ajman                     -332.71200
Abia                      -1475.55600
Abuja Capital Territory     -67.61400
Aceh                        -49.67430
Adamawa                    -289.02900
                              ...
Zealand                    -245.04300
Zeeland                    -100.17000
Zhambyl                     -28.59000
Zulia                      -994.14304
Šiauliai                   -164.73900
Name: Profit, Length: 290, dtype: float64

# City-wise Profitability Analysis.

In [48]:
city_wise_profit=df.groupby('City')['Profit'].sum().sort_values(ascending=False).head(10)

city_wise_profit

City
New York City    62036.98370
Los Angeles      30440.75790
Seattle          29156.09670
Managua          17853.71804
San Francisco    17507.38540
London           17378.71500
Sydney           16002.80700
Vienna           15660.84000
San Salvador     15036.51040
Mexico City      13342.29176
Name: Profit, dtype: float64

# Regional Profit Margin compare karo.

In [51]:
regional_sales=df.groupby('Region')['Sales'].sum()
regional_profit=df.groupby('Region')['Profit'].sum()

regional_analysis=(regional_profit/regional_sales)*100
regional_analysis

Region
Africa            11.338907
Canada            26.620137
Caribbean         10.660915
Central           11.033308
Central Asia      17.597413
EMEA               5.445155
East              13.482351
North             15.590386
North Asia        19.517725
Oceania           10.915138
South              8.766975
Southeast Asia     2.018494
West              14.943674
dtype: float64

# Discount aur Profit ka correlation kya hai?

In [5]:
correlation_value=df['Discount'].corr(df['Profit'])

print('\nCorrelation between Discount vs Profit:\n',correlation_value)
print('\nInsight:\nDiscount and Profit have a moderate negative correlation (-0.32). This suggests that increasing discounts tends to reduce profitability. While discounts may help drive sales, excessive discounting can negatively impact profit margins.')

Correlation between Discount vs Profit:
 -0.31649017182727096

Insight:
Discount and Profit have a moderate negative correlation (-0.32). This suggests that increasing discounts tends to reduce profitability. While discounts may help drive sales, excessive discounting can negatively impact profit margins.

# Kis discount range par sabse zyada profit milta hai?

In [11]:
bins = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]

labels = ['0-10%', '10-20%', '20-30%', '30-40%',
          '40-50%', '50-60%', '60-70%', '70-80%']

df['Discount_Range'] = pd.cut(
    df['Discount'],
    bins=bins,
    labels=labels,
    include_lowest=True
)

profit_of_discount_range = df.groupby('Discount_Range', observed=False)['Profit'].sum().sort_values(ascending=False).head()
print(round(profit_of_discount_range,2))

print('\nInsights:\nThe 0–10% discount range generated the highest profit. This indicates that low discounts are more effective at maintaining healthy profit margins. As discount levels increase, profitability tends to decline, suggesting that excessive discounting may be reducing overall profits.')

Discount_Range
0-10%     2108884.53
10-20%     173254.84
20-30%     -21155.61
70-80%     -38616.23
30-40%    -166115.45
Name: Profit, dtype: float64

Insights:
The 0–10% discount range generated the highest profit. This indicates that low discounts are more effective at maintaining healthy profit margins. As discount levels increase, profitability tends to decline, suggesting that excessive discounting may be reducing overall profits.

# High Discount Loss Cases identify karo.

In [14]:
bins = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]

labels = ['0-10%', '10-20%', '20-30%', '30-40%',
          '40-50%', '50-60%', '60-70%', '70-80%']

df['Discount_Range'] = pd.cut(
    df['Discount'],
    bins=bins,
    labels=labels,
    include_lowest=True
)

loss_of_discount_range = df.groupby('Discount_Range', observed=False)['Profit'].sum().sort_values(ascending=True).head()
print(round(loss_of_discount_range,2))

print('\nInsights:\nWhile low discount ranges (0–10%) produced the highest profits, the 40–50% discount range resulted in the highest losses. This indicates that excessive discounting erodes profit margins and increases the likelihood of loss-making transactions.')

Discount_Range
40-50%   -214829.37
60-70%   -197477.87
50-60%   -173418.91
30-40%   -166115.45
70-80%    -38616.23
Name: Profit, dtype: float64

Insights:
While low discount ranges (0–10%) produced the highest profits, the 40–50% discount range resulted in the highest losses. This indicates that excessive discounting erodes profit margins and increases the likelihood of loss-making transactions.

# Category-wise Discount Effect compare karo.

In [17]:
category_discount_effect = df.groupby('Category').agg(
    Avg_Discount=('Discount', 'mean'),
    Total_Profit=('Profit', 'sum')
)

category_discount_effect

                 Avg_Discount  Total_Profit
Category
Furniture            0.168087  285204.72380
Office Supplies      0.137409  518473.83430
Technology           0.135342  663778.73318

# Kya zyada discount sales badhata hai?

In [19]:
bins = [0, 0.1, 0.2, 0.3, 0.4, 0.5, 0.6, 0.7, 0.8]

labels = ['0-10%', '10-20%', '20-30%', '30-40%',
          '40-50%', '50-60%', '60-70%', '70-80%']

df['Discount_Range'] = pd.cut(
    df['Discount'],
    bins=bins,
    labels=labels,
    include_lowest=True
)

sales_of_discount_range=df.groupby('Discount_Range',observed=False)['Sales'].sum().sort_values(ascending=False)
sales_of_discount_range

Discount_Range
0-10%     8955367
10-20%    1757296
30-40%     701367
40-50%     474711
20-30%     382540
50-60%     199038
60-70%     151327
70-80%      20462
Name: Sales, dtype: int64

# Shipping Mode-wise Revenue.

In [22]:
df['Revenue']=df['Sales']*df['Quantity']

shipping_mode_wise_revenue=df.groupby('Ship.Mode')['Revenue'].sum().sort_values(ascending=False)
shipping_mode_wise_revenue

Ship.Mode
Standard Class    37085673
Second Class      12839800
First Class        8728752
Same Day           3168675
Name: Revenue, dtype: int64

# Shipping Mode-wise Profit.

In [23]:
shipping_mode_wise_profit=df.groupby('Ship.Mode')['Profit'].sum().sort_values(ascending=False)
shipping_mode_wise_profit

Ship.Mode
Standard Class    890596.02120
Second Class      292583.52708
First Class       208104.67520
Same Day           76173.06780
Name: Profit, dtype: float64

# Average Delivery Time Analysis (agar dates available hon).

In [40]:
df['Delivery_Date']=df['Ship.Date']-df['Order.Date']
df['Delivery_Day']=df['Delivery_Date'].dt.days

average_delivery_time_analysis=df['Delivery_Day'].mean()
average_delivery_time_analysis

np.float64(3.96937024761162)

# Fastest vs Most Profitable Shipping Mode.

In [42]:
fastestVSmost_profitable_ship_mode=df.groupby('Ship.Mode').agg(
    fastest_delivery_day=('Delivery_Day','mean'),
    total_profit=('Profit','sum')
)

fastestVSmost_profitable_ship_mode

                fastest_delivery_day  total_profit
Ship.Mode
First Class                 2.181746  208104.67520
Same Day                    0.037394   76173.06780
Second Class                3.230187  292583.52708
Standard Class              4.998018  890596.02120

# Shipping Cost ka Profit par impact.

In [46]:
ship_cost_profit_impact=df['Shipping.Cost'].corr(df['Profit'])
print(ship_cost_profit_impact)
print('\nInsights:\nOrders with higher shipping costs tend to generate higher profits, suggesting that larger or premium orders offset the additional shipping expense.')

0.3544408272343418

Insights:
Orders with higher shipping costs tend to generate higher profits, suggesting that larger or premium orders offset the additional shipping expense.